# antora generate playbook.yml
# antora generate --clean --to-dir public playbook.yml
site:
  title: 学习 C 语言
  url: https://peacetrue.github.io
  start_page: learn-c::index.adoc
asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml@'
    numbered: '@'
content:
  branches: master
  sources:
  - url: ../../
    start_path: docs/antora
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

